// GPIO 13; B 5
#define BUILTIN_LED_PORT PORTB
#define BUILTIN_LED_REGISTER DDRB
#define BUILTIN_LED_INDEX 5

// GPIO 11; B 3
// N64_RESET HIGH can damage your console
#define N64_RESET_PORT PORTB
#define N64_RESET_REGISTER DDRB
#define N64_RESET_INDEX 3

// GPIO 10; B 2
#define N64_CONTROLLER_PIN_ADDR 0x3
#define N64_CONTROLLER_REGISTER DDRB
#define N64_CONTROLLER_INDEX 2

#define RESET_COMBO (BUTTON_L | BUTTON_R | BUTTON_Z | BUTTON_A | BUTTON_B)
#define RESET_COOLDOWN_MS 5000
